<?php
namespace enrol_oneroster;

class csv_data_helper {
    public static function get_users_data() {
        return array(
            array(
                'sourcedId' => "student_01",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_01",
                'role' => "student",
                'username' => "student_01",
                'userIds' => NULL,
                'givenName' => "Clark",
                'familyName' => "Kent",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => "parent_01",
                'grades' => NULL,
                'password' => "CHANGEME",
            ),
            array(
                'sourcedId' => "student_02",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_01",
                'role' => "student",
                'username' => "student_02",
                'userIds' => NULL,
                'givenName' => "Lisa",
                'familyName' => "Kent",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => "parent_02",
                'grades' => NULL,
                'password' => "CHANGEME",
            ),
            array(
                'sourcedId' => "student_03",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_01",
                'role' => "student",
                'username' => "student_03",
                'userIds' => NULL,
                'givenName' => "Phil",
                'familyName' => "Kent",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => "parent_01",
                'grades' => NULL,
                'password' => "CHANGEME",
            ),
            array(
                'sourcedId' => "student_04",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_01",
                'role' => "student",
                'username' => "student_04",
                'userIds' => NULL,
                'givenName' => "Colin",
                'familyName' => "Ward",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => "parent_02",
                'grades' => NULL,
                'password' => "CHANGEME",
            ),
            array(
                'sourcedId' => "student_05",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_01",
                'role' => "student",
                'username' => "student_05",
                'userIds' => NULL,
                'givenName' => "Chris",
                'familyName' => "Ward",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => NULL,
                'grades' => "CHANGEME",
                'password' => NULL,
            ),
            array(
                'sourcedId' => "student_06",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_01",
                'role' => "student",
                'username' => "student_06",
                'userIds' => NULL,
                'givenName' => "Edward",
                'familyName' => "Smythe",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => NULL,
                'grades' => "CHANGEME",
                'password' => NULL,
            ),
            array(
                'sourcedId' => "student_07",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_01",
                'role' => "student",
                'username' => "student_07",
                'userIds' => NULL,
                'givenName' => "Tom",
                'familyName' => "Riddle",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => NULL,
                'grades' => "CHANGEME",
                'password' => NULL,
            ),
            array(
                'sourcedId' => "student_08",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_01",
                'role' => "student",
                'username' => "student_08",
                'userIds' => NULL,
                'givenName' => "Kelly",
                'familyName' => "Riddle",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => NULL,
                'grades' => "CHANGEME",
                'password' => NULL,
            ),
            array(
                'sourcedId' => "student_09",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_01",
                'role' => "student",
                'username' => "student_09",
                'userIds' => NULL,
                'givenName' => "Nick",
                'familyName' => "Baker",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => NULL,
                'grades' => "CHANGEME",
                'password' => NULL,
            ),
            array(
                'sourcedId' => "student_10",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_01",
                'role' => "student",
                'username' => "student_10",
                'userIds' => NULL,
                'givenName' => "Richard",
                'familyName' => "Bramall",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => NULL,
                'grades' => "CHANGEME",
                'password' => NULL,
            ),
            array(
                'sourcedId' => "student_11",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_02",
                'role' => "student",
                'username' => "student_11",
                'userIds' => NULL,
                'givenName' => "Stephen",
                'familyName' => "Knight",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => "parent_01",
                'grades' => NULL,
                'password' => "CHANGEME",
            ),
            array(
                'sourcedId' => "student_12",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_02",
                'role' => "student",
                'username' => "student_12",
                'userIds' => NULL,
                'givenName' => "Steven",
                'familyName' => "Rice",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => NULL,
                'grades' => "CHANGEME",
                'password' => NULL,
            ),
            array(
                'sourcedId' => "student_13",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_02",
                'role' => "student",
                'username' => "student_13",
                'userIds' => NULL,
                'givenName' => "Ben",
                'familyName' => "Roberts",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => NULL,
                'grades' => "CHANGEME",
                'password' => NULL,
            ),
            array(
                'sourcedId' => "student_14",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_02",
                'role' => "student",
                'username' => "student_14",
                'userIds' => NULL,
                'givenName' => "Sarah",
                'familyName' => "Coombes",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => NULL,
                'grades' => "CHANGEME",
                'password' => NULL,
            ),
            array(
                'sourcedId' => "student_15",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_02",
                'role' => "student",
                'username' => "student_15",
                'userIds' => NULL,
                'givenName' => "Laura",
                'familyName' => "Sellars",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => NULL,
                'grades' => "CHANGEME",
                'password' => NULL,
            ),
            array(
                'sourcedId' => "student_16",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_02",
                'role' => "student",
                'username' => "student_16",
                'userIds' => NULL,
                'givenName' => "Jennifer",
                'familyName' => "Marston",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => NULL,
                'grades' => "CHANGEME",
                'password' => NULL,
            ),
            array(
                'sourcedId' => "parent_01",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_01",
                'role' => "parent",
                'username' => "parent_01",
                'userIds' => NULL,
                'givenName' => "Martha",
                'familyName' => "Kent",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => "student_01,student_03",
                'grades' => NULL,
                'password' => "CHANGEME",
            ),
            array(
                'sourcedId' => "parent_02",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_01",
                'role' => "parent",
                'username' => "parent_02",
                'userIds' => NULL,
                'givenName' => "Jonathon",
                'familyName' => "Kent",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => "student_02,student_04",
                'grades' => NULL,
                'password' => "CHANGEME",
            ),
            array(
                'sourcedId' => "parent_03",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_02",
                'role' => "parent",
                'username' => "parent_03",
                'userIds' => NULL,
                'givenName' => "Bruce",
                'familyName' => "Wayne",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => NULL,
                'grades' => "CHANGEME",
                'password' => NULL,
            ),
            array(
                'sourcedId' => "parent_04",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_02",
                'role' => "parent",
                'username' => "parent_04",
                'userIds' => NULL,
                'givenName' => "Thomas",
                'familyName' => "Riddle",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => NULL,
                'grades' => "CHANGEME",
                'password' => NULL,
            ),
            array(
                'sourcedId' => "teacher_01",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_01",
                'role' => "teacher",
                'username' => "teacher_01",
                'userIds' => NULL,
                'givenName' => "Robert",
                'familyName' => "Ward",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => NULL,
                'grades' => "CHANGEME",
                'password' => NULL,
            ),
            array(
                'sourcedId' => "teacher_02",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_01",
                'role' => "teacher",
                'username' => "teacher_02",
                'userIds' => NULL,
                'givenName' => "Anne",
                'familyName' => "Ward",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => NULL,
                'grades' => "CHANGEME",
                'password' => NULL,
            ),
            array(
                'sourcedId' => "teacher_03",
                'status' => NULL,
                'dateLastModified' => NULL,
                'enabledUser' => True,
                'orgSourcedIds' => "ORG_02",
                'role' => "teacher",
                'username' => "teacher_03",
                'userIds' => NULL,
                'givenName' => "Rose",
                'familyName' => "Smythe",
                'middleName' => NULL,
                'identifier' => NULL,
                'email' => NULL,
                'sms' => NULL,
                'phone' => NULL,
                'agentSourcedIds' => NULL,
                'grades' => "CHANGEME",
                'password' => NULL,
            ),
        );
    }

    public static function get_classes_data() {
        return array(
            array(
                'sourcedId' => "CLASS_01",
                'status' => NULL,
                'dateLastModified' => NULL,
                'title' => "1st Grade Math Sem A - Mrs. Smith",
                'grades' => NULL,
                'courseSourcedId' => "COURSE_01",
                'classCode' => NULL,
                'classType' => "scheduled",
                'location' => NULL,
                'schoolSourcedId' => "ORG_01",
                'termSourcedIds' => "ACADSESS_01",
                'subjects' => NULL,
                'subjectCodes' => NULL,
                'periods' => NULL,
            ),
            array(
                'sourcedId' => "CLASS_02",
                'status' => NULL,
                'dateLastModified' => NULL,
                'title' => "American History Sem B - Mr. Jones",
                'grades' => NULL,
                'courseSourcedId' => "COURSE_01",
                'classCode' => NULL,
                'classType' => "scheduled",
                'location' => NULL,
                'schoolSourcedId' => "ORG_01",
                'termSourcedIds' => "ACADSESS_01",
                'subjects' => NULL,
                'subjectCodes' => NULL,
                'periods' => NULL,
            ),
            array(
                'sourcedId' => "CLASS_03",
                'status' => NULL,
                'dateLastModified' => NULL,
                'title' => "Digital Photography - Dr. Spock",
                'grades' => NULL,
                'courseSourcedId' => "COURSE_02",
                'classCode' => NULL,
                'classType' => "scheduled",
                'location' => NULL,
                'schoolSourcedId' => "ORG_01",
                'termSourcedIds' => "ACADSESS_01",
                'subjects' => NULL,
                'subjectCodes' => NULL,
                'periods' => NULL,
            ),
            array(
                'sourcedId' => "CLASS_04",
                'status' => NULL,
                'dateLastModified' => NULL,
                'title' => "US History - Section 9 - Mr. Jones",
                'grades' => NULL,
                'courseSourcedId' => "COURSE_03",
                'classCode' => NULL,
                'classType' => "scheduled",
                'location' => NULL,
                'schoolSourcedId' => "ORG_02",
                'termSourcedIds' => "ACADSESS_01",
                'subjects' => NULL,
                'subjectCodes' => NULL,
                'periods' => NULL,
            ),
        );
    }

    public static function get_courses_data() {
        return array(
            array(
                'sourcedId' => "COURSE_01",
                'status' => NULL,
                'dateLastModified' => NULL,
                'schoolYearSourcedId' => NULL,
                'title' => "1st Grade Math Sem A",
                'courseCode' => NULL,
                'grades' => NULL,
                'orgSourcedId' => "ORG_01",
                'subjects' => NULL,
                'subjectCodes' => NULL,
            ),
            array(
                'sourcedId' => "COURSE_02",
                'status' => NULL,
                'dateLastModified' => NULL,
                'schoolYearSourcedId' => NULL,
                'title' => "American History Sem B",
                'courseCode' => NULL,
                'grades' => NULL,
                'orgSourcedId' => "ORG_01",
                'subjects' => NULL,
                'subjectCodes' => NULL,
            ),
            array(
                'sourcedId' => "COURSE_03",
                'status' => NULL,
                'dateLastModified' => NULL,
                'schoolYearSourcedId' => NULL,
                'title' => "Digital Photography",
                'courseCode' => NULL,
                'grades' => NULL,
                'orgSourcedId' => "ORG_02",
                'subjects' => NULL,
                'subjectCodes' => NULL,
            ),
        );
    }
    public static function get_orgs_data() {
        return array(
            array(
                'sourcedId' => "ORG_01",
                'status' => NULL,
                'dateLastModified' => NULL,
                'name' => "METROPOLIS ELEMENTARY",
                'type' => "school",
                'identifier' => NULL,
                'parentSourcedId' => "ORG_04",
            ),
            array(
                'sourcedId' => "ORG_02",
                'status' => NULL,
                'dateLastModified' => NULL,
                'name' => "METROPOLIS MIDDLE",
                'type' => "school",
                'identifier' => NULL,
                'parentSourcedId' => "ORG_04",
            ),
            array(
                'sourcedId' => "ORG_03",
                'status' => NULL,
                'dateLastModified' => NULL,
                'name' => "METROPOLIS HIGHSCHOOL",
                'type' => "school",
                'identifier' => NULL,
                'parentSourcedId' => "ORG_04",
            ),
            array(
                'sourcedId' => "ORG_04",
                'status' => NULL,
                'dateLastModified' => NULL,
                'name' => "METROPOLIS SCHOOL DISTRICT",
                'type' => "district",
                'identifier' => NULL,
                'parentSourcedId' => NULL,
            ),
        );
    } 
    
    public static function get_manifest_data() {
        return array(
            array(
                'propertyName' => "manifest.version",
                'value' => "1.0",
            ),
            array(
                'propertyName' => "oneroster.version",
                'value' => "1.1",
            ),
            array(
                'propertyName' => "file.academicSessions",
                'value' => "bulk",
            ),
            array(
                'propertyName' => "file.categories",
                'value' => "absent",
            ),
            array(
                'propertyName' => "file.classes",
                'value' => "bulk",
            ),
            array(
                'propertyName' => "file.classResources",
                'value' => "absent",
            ),
            array(
                'propertyName' => "file.courses",
                'value' => "bulk",
            ),
            array(
                'propertyName' => "file.courseResources",
                'value' => "absent",
            ),
            array(
                'propertyName' => "file.demographics",
                'value' => "absent",
            ),
            array(
                'propertyName' => "file.enrollments",
                'value' => "bulk",
            ),
            array(
                'propertyName' => "file.lineItems",
                'value' => "absent",
            ),
            array(
                'propertyName' => "file.orgs",
                'value' => "bulk",
            ),
            array(
                'propertyName' => "file.resources",
                'value' => "absent",
            ),
            array(
                'propertyName' => "file.results",
                'value' => "absent",
            ),
            array(
                'propertyName' => "file.users",
                'value' => "bulk",
            ),
            array(
                'propertyName' => "source.systemCode",
                'value' => "absent",
            ),
            array(
                'propertyName' => "source.systemName",
                'value' => "absent",
            ),
        );
    }

    public static function get_enrollments_data() {
        return array(
            array(
                'sourcedId' => "en0001",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_01",
                'schoolSourcedId' => "ORG_01",
                'userSourcedId' => "student_01",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0002",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_01",
                'schoolSourcedId' => "ORG_01",
                'userSourcedId' => "student_02",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0003",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_01",
                'schoolSourcedId' => "ORG_01",
                'userSourcedId' => "student_03",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0004",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_01",
                'schoolSourcedId' => "ORG_01",
                'userSourcedId' => "student_04",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0005",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_01",
                'schoolSourcedId' => "ORG_01",
                'userSourcedId' => "student_05",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0006",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_01",
                'schoolSourcedId' => "ORG_01",
                'userSourcedId' => "student_06",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0007",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_01",
                'schoolSourcedId' => "ORG_01",
                'userSourcedId' => "student_07",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0008",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_02",
                'schoolSourcedId' => "ORG_01",
                'userSourcedId' => "student_08",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0009",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_02",
                'schoolSourcedId' => "ORG_01",
                'userSourcedId' => "student_09",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0010",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_02",
                'schoolSourcedId' => "ORG_01",
                'userSourcedId' => "student_10",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0011",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_04",
                'schoolSourcedId' => "ORG_02",
                'userSourcedId' => "student_11",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0012",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_04",
                'schoolSourcedId' => "ORG_02",
                'userSourcedId' => "student_12",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0013",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_04",
                'schoolSourcedId' => "ORG_02",
                'userSourcedId' => "student_13",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0014",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_04",
                'schoolSourcedId' => "ORG_02",
                'userSourcedId' => "student_14",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0015",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_04",
                'schoolSourcedId' => "ORG_02",
                'userSourcedId' => "student_15",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0016",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_04",
                'schoolSourcedId' => "ORG_02",
                'userSourcedId' => "student_16",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0017",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_03",
                'schoolSourcedId' => "ORG_01",
                'userSourcedId' => "student_01",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0018",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_03",
                'schoolSourcedId' => "ORG_01",
                'userSourcedId' => "student_02",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0019",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_03",
                'schoolSourcedId' => "ORG_01",
                'userSourcedId' => "student_03",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0020",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_03",
                'schoolSourcedId' => "ORG_01",
                'userSourcedId' => "student_04",
                'role' => "student",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0021",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_01",
                'schoolSourcedId' => "ORG_01",
                'userSourcedId' => "teacher_01",
                'role' => "teacher",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0022",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_02",
                'schoolSourcedId' => "ORG_01",
                'userSourcedId' => "teacher_01",
                'role' => "teacher",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' => "en0023",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_03",
                'schoolSourcedId' => "ORG_01",
                'userSourcedId' => "teacher_02",
                'role' => "teacher",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
            array(
                'sourcedId' =>  "en0024",
                'status' => NULL,
                'dateLastModified' => NULL,
                'classSourcedId' => "CLASS_04",
                'schoolSourcedId' => "ORG_02",
                'userSourcedId' => "teacher_03",
                'role' => "teacher",
                'primary' => NULL,
                'beginDate' => NULL,
                'endDate' => NULL,
            ),
        );
    }

    public static function get_academicSessions_data() {
        return array(
            array(
                'sourcedId' => "ACADSESS_01",
                'status' => NULL,
                'dateLastModified' => NULL,
                'title' => "Fall 2019",
                'type' => "semester",
                'startDate' => "19-08-2019",
                'endDate' => "18-01-2020",
                'parentSourcedId' => NULL,
                'schoolYear' => 2020,
            ),
            array(
                'sourcedId' => "ACADSESS_02",
                'status' => NULL,
                'dateLastModified' => NULL,
                'title' => "Spring 2020",
                'type' => "semester",
                'startDate' => "19-01-2020",
                'endDate' => "30-06-2020",
                'parentSourcedId' => NULL,
                'schoolYear' => 2020,
            ),
        );
    }
}